name: Build Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Crear zip solo con contenido de carpeta1
        run: |
          mkdir release-content
          cp carpeta1/* release-content/
          zip -r prueba-1.0.${{ github.run_number }}.zip release-content

      - name: Crear Release con gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create 1.0.${{ github.run_number }} prueba-1.0.${{ github.run_number }}.zip \
            --target ${{ github.sha }} \
            -t "Prueba 1 1.0.${{ github.run_number }}" \
            -n "Release de prueba 1 generado automáticamente (run #${{ github.run_number }})"
