name: Build Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Crear zip solo con contenido de carpeta1
        run: |
          mkdir release-content
          cp carpeta1/* release-content/
          zip -r prueba.zip release-content

      - name: Instalar GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Crear Release con gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create 1.0.${{ github.run_number }} prueba.zip \
            --target ${{ github.sha }} \
            -t "Prueba 1" \
            -n "Release de prueba 1 generado automáticamente (run #${{ github.run_number }})"
